' < sabrown |X| D12_05_05_09_02_53 | Remote fiona > Improvements in import-api process'

diff --git a/trunk/source/scripts/import-api b/trunk/source/scripts/import-api
--- a/trunk/source/scripts/import-api
+++ b/trunk/source/scripts/import-api
@@ -126,6 +126,12 @@ if ("$#arc" > 1) then
    endif
 endif
 
+# start a blank file now
+# if it exits after this there will at least be a file
+# that make can check for dependencies
+rm -f $api >& /dev/null
+touch $api
+
 set ok  = FALSE
 set hdr = ( `grep -w header $def` )
 set hdr = $hdr[2]
@@ -146,8 +152,6 @@ if ("$api" == "") then
    set api = $pck.api
 endif
 echo "   Generating '$api' from '$hdr'"
-rm -f $api
-touch $api
 
 #--------------------------------------------------------------------------
 #--------------------------------------------------------------------------
@@ -173,12 +177,13 @@ endif
 #--------------------------------------------------------------------------
 #--------------------------------------------------------------------------
 
-set fncl = ""
-
+set fncl    = ""
+set varl    = ""
 set missing = ""
 
 # look for specified functions to bind
-set ok = FALSE
+set fok = FALSE
+set vok = FALSE
 @ nl = `cat $def | wc -l`
 @ il = 0
 while ($il < $nl)
@@ -187,17 +192,30 @@ while ($il < $nl)
    if ("$line" == "") continue
    if ("$line" =~ \#*) continue
    if ("$line" =~ *functions\ \{) then
-      set ok = TRUE
+      set fok = TRUE
+      continue
+   endif
+   if ("$line" =~ *variables\ \{) then
+      set vok = TRUE
       continue
    endif
    if ("$line" =~ *\}*) then
-      set ok = FALSE
+      set fok = FALSE
+      set vok = FALSE
       continue
    endif
-   if ($ok == TRUE) then
+   if ($fok == TRUE) then
       grep -w $line $ppf >& /dev/null
       if ($status == 0) then
          set fncl = ( $fncl $line )
+      else
+         set missing = ( $missing $line )
+      endif
+
+   else if ($vok == TRUE) then
+      grep -w $line $ppf >& /dev/null
+      if ($status == 0) then
+         set varl = ( $varl $line )
       else
          set missing = ( $missing $line )
       endif
@@ -225,23 +243,34 @@ if ("$fncl" == "") then
    unset noglob
 endif
 
+if ("$varl" == "") then
+   @ nv = 0
+else
+   @ nv = $#varl
+endif
+
 # it is an error to specify no functions
+# however we must generate a dummy API
+@ nf = $#fncl
 if ("$fncl" == "") then
-   echo "No functions found in $ppf - exiting"
+   echo "   Warning: no functions found in $ppf"
    cat $ppf
-   exit($fatal)
+   @ nf = 0
+   @ nm = 0
 
 else if ("$missing" != "") then
-   if ($#missing == $#fncl) then
-      echo "All $#missing functions missing in $ppf - exiting"
+   @ nm = $#missing
+   if ($nm == $nf) then
+      echo "   Warning: all $nm functions missing in $ppf"
       cat $ppf
-      exit($fatal)
    else
       set t = $hdr:t
-      echo "Missing $#missing out of $#fncl requested functions for ${t}:"
+      @ n  = $nf + $nm
+      echo "   Warning: missing $nm out of $n requested functions or variables for ${t}"
       foreach f ($missing)
-         echo "   $f"
+         echo "      $f"
       end
+      unset n
       unset t
       @ nwarn = $nwarn + 4
    endif
@@ -264,24 +293,33 @@ Note $api "#define ${PCK}_API_PACT"
 Note $api ''
 Note $api '#include <'$hdr:t'>'
 Note $api ''
-Note $api "typedef struct s_${pck}_api ${pck}_api;"
-Note $api ''
-Note $api "struct s_${pck}_api"
-Note $api '   {'
 
-set noglob
-foreach f ($fncl)
-   set m = '(*f'$f')'
-   set t = ( `grep -w $f $ppf | sed "s|$f|$m|"` )
-   Note $api "    $t"
-end
-unset noglob
+if (($nf > 0) || ($nv > 0)) then
+   Note $api "typedef struct s_${pck}_api ${pck}_api;"
+   Note $api ''
+   Note $api "struct s_${pck}_api"
+   Note $api '   {'
 
-Note $api '   };'
-Note $api ''
-Note $api "static ${pck}_api"
-Note $api " _${pck}_;"
-Note $api ''
+   set noglob
+   foreach v ($varl)
+      set m = v$v
+      set t = ( `grep -w $v $ppf | sed "s|$v|*$m|"` )
+      Note $api "    $t"
+   end
+   foreach f ($fncl)
+      set m = '(*f'$f')'
+      set t = ( `grep -w $f $ppf | sed "s|$f|$m|"` )
+      Note $api "    $t"
+   end
+   unset noglob
+
+   Note $api '   };'
+   Note $api ''
+   Note $api "static ${pck}_api"
+   Note $api " _${pck}_;"
+   Note $api ''
+endif
+
 Note $api '/*--------------------------------------------------------------------------*/'
 Note $api '/*--------------------------------------------------------------------------*/'
 Note $api ''
@@ -291,55 +329,73 @@ Note $api "void _${PCK}_set_api(void)"
 Note $api '   {'
 Note $api ''
 
-set m = f$fncl[1]
-Note $api "    if (_${pck}_.$m == NULL)"
+if (($nf > 0) || ($nv > 0)) then
+   set m = f$fncl[1]
+   Note $api "    if (_${pck}_.$m == NULL)"
 
-Note $api ''
-Note $api "#ifdef ${PCK}_SO"
-Note $api ''
-Note $api '/* dynamically linked way */'
-Note $api '       {int rv;'
-Note $api ''
-Note $api '	rv = SC_so_register_func(OBJ_SO, "'${so}'", "'${pck}'",'
-Note $api '				 NULL, NULL, NULL, NULL);'
-Note $api '	if (rv == FALSE)'
-Note $api '	   SC_error(-1, "CANNOT LOAD '${so}'");'
-Note $api ''
+   Note $api ''
+   Note $api "#ifdef ${PCK}_SO"
+   Note $api ''
+   Note $api '/* dynamically linked way */'
+   Note $api '       {int rv;'
+   Note $api ''
 
-foreach f ($fncl)
-   set m = f$f
-   Note $api "	_${pck}_.$m \t = SC_so_get(OBJ_SO, "'"'${pck}'", "'$f'");'
-end
+   Note $api "	rv = SC_so_register_func(OBJ_SO, ${PCK}_SO, "'"'${pck}'",'
+   Note $api '				 NULL, NULL, NULL, NULL);'
+   Note $api '	if (rv == FALSE)'
+   Note $api '	   SC_error(-1, "CANNOT LOAD '${so}'");'
+   Note $api ''
 
-Note $api '       }'
-Note $api ''
-Note $api '#else'
-Note $api ''
-Note $api '/* statically linked way */'
-Note $api '       {'
-Note $api ''
+   foreach v ($varl)
+      set m = v$v
+      Note $api "	_${pck}_.$m \t = SC_so_get(OBJ_SO, "'"'${pck}'", "'$v'");'
+   end
+   foreach f ($fncl)
+      set m = f$f
+      Note $api "	ASSIGN_FNC(_${pck}_.$m, \t SC_so_get(OBJ_SO, "'"'${pck}'", "'$f'"));'
+   end
 
-foreach f ($fncl)
-   set m = f$f
-   Note $api "	_${pck}_.$m \t = $f;"
-end
+   Note $api '       }'
+   Note $api ''
+   Note $api '#else'
+   Note $api ''
+   Note $api '/* statically linked way */'
+   Note $api '       {'
+   Note $api ''
 
-Note $api '       };'
-Note $api ''
-Note $api '#endif'
-Note $api ''
+   foreach v ($varl)
+      set m = v$v
+      Note $api "	_${pck}_.$m \t = &$v;"
+   end
+   foreach f ($fncl)
+      set m = f$f
+      Note $api "	_${pck}_.$m \t = $f;"
+   end
+
+   Note $api '       };'
+   Note $api ''
+   Note $api '#endif'
+   Note $api ''
+endif
+
 Note $api '    return;}'
 Note $api ''
 Note $api '/*--------------------------------------------------------------------------*/'
 Note $api '/*--------------------------------------------------------------------------*/'
 Note $api ''
 
-foreach f ($fncl)
-   set m = f$f
-   Note $api "#define $f \t _${pck}_.$m"
-end
+if (($nf > 0) || ($nv > 0)) then
+   foreach v ($varl)
+      set m = v$v
+      Note $api "#define $v \t "'*('_${pck}_.$m')'
+   end
+   foreach f ($fncl)
+      set m = f$f
+      Note $api "#define $f \t _${pck}_.$m"
+   end
+   Note $api ''
+endif
 
-Note $api ''
 Note $api '#endif'
 Note $api ''
 
@@ -351,11 +407,11 @@ if (!(-f $api)) then
 endif
 
 if ($nwarn > 0) then
-   echo "Completed with warnings $nwarn"
+   echo "   Completed with warning status $nwarn"
 endif
 
 if ($keep == FALSE) then
-   rm -rf $ppf
+   rm -rf $ppf >& /dev/null
 endif
 
 #--------------------------------------------------------------------------
